name: WhapplePay
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: 3.16.5

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.1.0
  country_code_picker: ^3.2.0
  get_storage: ^2.1.1
  logger: ^2.5.0
  pin_code_fields: 8.0.1
  intl: 0.19.0
  image_picker: ^0.8.5
  dotted_line: ^3.2.3
  flutter_svg: ^0.22.0 
#  percent_indicator: ^4.2.3
  qr_code_scanner: ^1.0.1
  flip_card: ^0.7.0
  dotted_border: 2.1.0
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.0.3
  flutter_spinkit: ^5.2.1
  smooth_page_indicator: ^1.2.0
  http: 1.1.2
  flutter_inappwebview: ^6.0.0
  patterns_canvas: 0.5.0
  flutter_html: ^2.0.0
  share_plus: ^7.0.2
  local_auth: ^2.1.8
  cached_network_image: ^3.2.0
  path_provider: ^2.1.1
  uuid: ^3.0.0
  flutter_local_notifications: ^18.0.1
  iconsax: ^0.0.8
  flutter_animate: ^4.5.2 
  flutter_staggered_animations: ^1.1.1
  qr_flutter: ^4.1.0
  liquid_swipe: ^3.1.0
  pusher_beams: ^1.1.1
  firebase_core: ^3.4.0
  rename_app: ^1.6.1
  flutter_phoenix: ^1.1.1
  restart_app: ^1.0.0
  r_dotted_line_border: ^0.1.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  change_app_package_name: ^1.1.0
  flutter_lints: ^3.0.0
  build_runner: ^2.1.5
  flutter_gen_runner: ^4.0.0
  dart_code_metrics: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo/app_launcher.png"

flutter_gen:
  output: lib/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

flutter:
  uses-material-design: true

  fonts:
    - family: AgencyFB-Bold
      fonts:
        - asset: fonts/AgencyFB-Bold.ttf

  assets:
    - assets/card/
    - assets/clipart/
    - assets/icon/
    - assets/icon/agent.svg
    - assets/logo/
    - assets/qr/
